name: Get Repository ID

on:
  workflow_dispatch:

jobs:
  get_repository_id:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Repository ID
        uses: actions/github-script@v6
        with:
          script: |
            const { context, Octokit } = require('@actions/github');
            const github = new Octokit();
            async function getRepositoryId() {
              const { data: { repository: { id } } } = await github.rest.repos.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
              });
              return id;
            }
            const repositoryId = await getRepositoryId();
            console.log(`Repository ID: ${repositoryId}`);
            core.setOutput('repositoryId', repositoryId);
