name: Update Documentation

on:
  pull_request:
    paths:
      - 'roles/*/defaults/main.yaml'
      - 'roles/*/Chart.yaml'
      - 'roles/*/README.md.gotmpl'

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install package
        env:
          HELM_DOCS_URL: https://github.com/norwoodj/helm-docs/releases/download
          HELM_DOCS_VERSION: 1.14.2
        run: |
          sudo wget -qP /tmp $HELM_DOCS_URL/v${HELM_DOCS_VERSION}/helm-docs_${HELM_DOCS_VERSION}_Linux_x86_64.deb
          sudo apt-get -y install /tmp/helm-docs_${HELM_DOCS_VERSION}_Linux_x86_64.deb

      - name: Update documentation
        run: |
          git config user.email '${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com'
          git config user.name '${{ github.actor }}'
          git fetch
          git switch ${{ github.head_ref }}
          helm-docs --values-file=./defaults/main.yaml

      - name: Get repository id
        uses: actions/github-script@v7
        with:
          script: |
            async function getRepositoryId(owner, repo) {
              try {
                const { data: { repository: { id } } } = await github.rest.repos.get({
                  owner: owner,
                  repo: repo,
                });
                return id;
              } catch (error) {
                console.error(`Error fetching repository data for ${owner}/${repo}:`, error);
                return null; 
              }
            }
            const owner = process.env.GITHUB_REPOSITORY.split("/")[0];
            const repo = process.env.GITHUB_REPOSITORY.split("/")[1];
            const repositoryId = await getRepositoryId(owner, repo);
            console.log(`Repository ID for ${owner}/${repo}: ${repositoryId}`);
            core.setOutput('repositoryId', repositoryId);
