name: Update Documentation
on:
  pull_request:
    paths:
      - 'roles/*/defaults/main.yaml'
      - 'roles/*/Chart.yaml'
      - 'roles/*/README.md.gotmpl'
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
defaults:
  run:
    shell: bash
jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install required packages
        env:
          HELM_DOCS_URL: https://github.com/norwoodj/helm-docs/releases/download
          HELM_DOCS_VERSION: 1.14.2
        run: |
          sudo wget -qP /tmp $HELM_DOCS_URL/v${HELM_DOCS_VERSION}/helm-docs_${HELM_DOCS_VERSION}_Linux_x86_64.deb
          sudo apt-get -y install jq /tmp/helm-docs_${HELM_DOCS_VERSION}_Linux_x86_64.deb
      - name: Update documentation
        id: update
        run: |
          git config user.email '${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com'
          git config user.name '${{ github.actor }}'
          git fetch
          git switch ${{ github.head_ref }}
          helm-docs --values-file=./defaults/main.yaml
          if [ -n "$(git ls-files -om --deduplicate)" ]; then
            echo "::set-output name=files::$(git ls-files -om --deduplicate | jq -Rsc 'split("\n")[:-1]')"
          else
            echo "::set-output name=files::[]"
          fi
      - name: Commit changes
        env:
          GITHUB_BRANCH_NAME: ${{ github.head_ref }}
          GITHUB_COMMIT_MESSAGE: 'docs(github-action): update documentation'
          GITHUB_TOKEN: ${{ github.token }}
        if: steps.update.outputs.files != '[]'
        run: node .github/api/commit.js "${{ steps.update.outputs.files }}"
permissions:
  contents: write
